project 'InterestingNews.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InterestingNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InterestingNews

  target 'InterestingNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterestingNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'ASIHTTPRequest'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'SVPullToRefresh'
  pod 'XRCarouselView'

end